# Web Navigation Playbook
# Guides autonomous web navigation for learning and research

name: web_navigation
version: 1.0.0
priority: medium

metadata:
  description: Autonomous web navigation and learning strategies
  owner: autonomous_web_navigator
  auto_trigger: false
  requires_approval: true  # Require approval for web navigation
  
strategies:
  - name: research_topic
    description: Research a topic by navigating trusted sources
    steps:
      - identify_trusted_sources
      - navigate_to_documentation
      - extract_key_information
      - store_with_provenance
      
  - name: learn_technology
    description: Learn a new technology or framework
    steps:
      - find_official_documentation
      - read_getting_started_guide
      - explore_api_reference
      - find_code_examples
      - test_in_sandbox
      
  - name: competitive_research
    description: Research competitor websites (with governance)
    steps:
      - request_guardian_approval
      - navigate_to_site
      - analyze_features
      - extract_patterns
      - document_findings
      
trusted_domains:
  documentation:
    - docs.python.org
    - developer.mozilla.org
    - reactjs.org
    - vuejs.org
    - golang.org
    - rust-lang.org
    
  tutorials:
    - realpython.com
    - freecodecamp.org
    - w3schools.com
    - tutorialspoint.com
    
  api_references:
    - api.github.com
    - developers.google.com
    - stripe.com/docs
    - aws.amazon.com/documentation
    
  code_repositories:
    - github.com
    - gitlab.com
    - bitbucket.org
    
navigation_rules:
  max_depth: 3
  max_pages_per_session: 20
  timeout_per_page: 30
  respect_robots_txt: true
  user_agent: "Grace AI Learning Bot/1.0"
  
  allowed_actions:
    - read_page
    - follow_links
    - download_documentation
    - extract_code_examples
    
  forbidden_actions:
    - submit_forms
    - create_accounts
    - make_purchases
    - post_comments
    - execute_scripts
    
governance:
  require_approval_for:
    - new_domains
    - form_submissions
    - file_downloads
    - api_calls
    
  auto_approve:
    - trusted_documentation_sites
    - read_only_operations
    
  always_log:
    - urls_visited
    - data_extracted
    - approval_requests
    - governance_decisions
    
learning_patterns:
  - pattern: official_documentation
    priority: high
    strategy:
      - navigate_to_root
      - find_getting_started
      - read_core_concepts
      - explore_api_reference
      - download_examples
      
  - pattern: tutorial_series
    priority: medium
    strategy:
      - identify_tutorial_structure
      - follow_sequential_order
      - extract_code_snippets
      - note_best_practices
      
  - pattern: api_exploration
    priority: high
    strategy:
      - read_api_overview
      - study_authentication
      - learn_common_endpoints
      - understand_rate_limits
      - extract_code_examples

quality_checks:
  before_ingestion:
    - verify_content_length > 100
    - check_not_error_page
    - validate_html_structure
    - ensure_relevant_to_topic
    
  after_ingestion:
    - verify_stored_correctly
    - check_provenance_recorded
    - ensure_searchable
    - validate_metadata

error_handling:
  on_navigation_error:
    - log_error
    - try_alternative_source
    - notify_if_critical
    
  on_quota_exceeded:
    - pause_learning
    - notify_guardian
    - schedule_resume
    
  on_blocked_access:
    - respect_robots_txt
    - try_alternative_approach
    - escalate_if_needed

metrics:
  track:
    - pages_visited
    - domains_explored
    - knowledge_extracted
    - navigation_errors
    - approval_requests
    - governance_blocks
    
  success_criteria:
    - knowledge_quality > 0.7
    - navigation_efficiency > 0.6
    - error_rate < 0.1
